use_frameworks!

target 'iExtra_Example' do
  pod 'iExtra', :path => '../'

  target 'iExtra_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.1.0'
    pod 'Quick', :git => 'https://github.com/Quick/Quick.git' , :branch => 'master'
    #pod 'Nimble', '~> 7.0.1'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git' , :branch => 'master'
  end
end
